FROM php:8.2-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libpq-dev \
    gnupg \
    && docker-php-ext-install pdo pdo_mysql mbstring zip exif pcntl bcmath

# ✨ Cài MongoDB extension
RUN pecl install mongodb && docker-php-ext-enable mongodb

COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --ignore-platform-reqs --no-interaction --prefer-dist --optimize-autoloader

RUN chown -R www-data:www-data /var/www \
    && chmod -R 755 /var/www/storage

EXPOSE 8000

CMD php artisan serve --host=0.0.0.0 --port=8000
